/**
 * Numerical-parity tests for the TypeScript landmark pipeline against
 * the canonical Python implementation.
 *
 * The fixture file ``landmark_fixtures.json`` is generated by
 * ``openhand-model/scripts/dump_landmark_vectors.py`` whenever the
 * canonical Python pipeline changes. We assert that the TS
 * ``buildFrameFeatures`` produces a byte-identical packing and that
 * ``normalizeSequence`` produces output matching within float32
 * precision (~1e-4) for a known sequence.
 *
 * If this test fails, the TS port has drifted from the training-time
 * Python code and the deployed CTC model will silently produce nonsense
 * until the drift is fixed.
 */

import { describe, expect, it } from "vitest";

import {
  FRAME_FEATURES,
  FRAME_LANDMARKS,
  buildFrameFeatures,
  normalizeSequence,
} from "../landmarks";
import fixtures from "./landmark_fixtures.json";

const NORM_TOLERANCE = 1e-4;

describe("landmarks parity (Python ↔ TypeScript)", () => {
  it("derived constants match the fixture", () => {
    expect(FRAME_FEATURES).toBe(fixtures.metadata.n_features);
    expect(FRAME_LANDMARKS).toBe(fixtures.metadata.n_landmarks);
  });

  it("buildFrameFeatures packs features byte-identically", () => {
    const out = buildFrameFeatures(fixtures.raw_frame);
    expect(out.features.length).toBe(fixtures.packed_features.length);

    // Track and report the first mismatch instead of dumping 381 values.
    for (let i = 0; i < out.features.length; i++) {
      expect(out.features[i]).toBeCloseTo(fixtures.packed_features[i], 6);
    }
  });

  it("buildFrameFeatures produces the expected missing mask", () => {
    const out = buildFrameFeatures(fixtures.raw_frame);
    expect(out.missing.length).toBe(fixtures.packed_missing.length);
    for (let i = 0; i < out.missing.length; i++) {
      const jsBool = out.missing[i] !== 0;
      const pyBool = !!fixtures.packed_missing[i];
      expect(jsBool).toBe(pyBool);
    }
  });

  it("normalizeSequence matches Python within float32 precision", () => {
    const T = fixtures.metadata.n_frames_for_normalize;
    const inFeatures = new Float32Array(fixtures.normalized_input_features);
    const inMissing = new Uint8Array(fixtures.normalized_input_missing.length);
    for (let i = 0; i < fixtures.normalized_input_missing.length; i++) {
      inMissing[i] = fixtures.normalized_input_missing[i] ? 1 : 0;
    }
    const out = normalizeSequence(inFeatures, inMissing, T);

    expect(out.length).toBe(fixtures.normalized_features.length);
    let maxDiff = 0;
    let maxDiffI = -1;
    for (let i = 0; i < out.length; i++) {
      const d = Math.abs(out[i] - fixtures.normalized_features[i]);
      if (d > maxDiff) {
        maxDiff = d;
        maxDiffI = i;
      }
    }
    expect(
      maxDiff,
      `max diff ${maxDiff.toExponential(2)} at index ${maxDiffI}`,
    ).toBeLessThan(NORM_TOLERANCE);
  });
});
