/**
 * Validation harness for the TypeScript landmark pipeline.
 *
 * Loads ``landmark_fixtures.json`` (regenerated by
 * ``openhand-model/scripts/dump_landmark_vectors.py`` whenever the
 * canonical Python pipeline changes) and confirms the TS port produces
 * byte-identical packing and near-identical normalisation.
 *
 * Run with: `node --experimental-strip-types src/lib/__tests__/landmarks.test.mjs`
 * (Node 22+ runs .ts/.mts directly; we use .mjs and dynamic-import the .ts
 *  via Vite's runtime in a real test framework. For this MVP harness we
 *  re-implement just enough to exercise the public API by importing the
 *  source after a quick TypeScript → JavaScript transform via tsx/esbuild.
 *  In practice we run this via `npm test` once vitest is added; for now
 *  it runs under tsx.)
 */

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildFrameFeatures,
  normalizeSequence,
  FRAME_FEATURES,
  FRAME_LANDMARKS,
} from "../landmarks.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixturesPath = resolve(here, "landmark_fixtures.json");
const fixtures = JSON.parse(readFileSync(fixturesPath, "utf8"));

let pass = 0;
let fail = 0;

function check(name, condition, detail) {
  if (condition) {
    pass++;
    console.log(`  ✓ ${name}`);
  } else {
    fail++;
    console.error(`  ✗ ${name}${detail ? `: ${detail}` : ""}`);
  }
}

console.log("Landmark pipeline validation");
console.log(`  fixture metadata: ${JSON.stringify(fixtures.metadata)}`);

// 1. Constants match.
check(
  "FRAME_FEATURES matches fixture",
  FRAME_FEATURES === fixtures.metadata.n_features,
  `got ${FRAME_FEATURES} want ${fixtures.metadata.n_features}`,
);
check(
  "FRAME_LANDMARKS matches fixture",
  FRAME_LANDMARKS === fixtures.metadata.n_landmarks,
  `got ${FRAME_LANDMARKS} want ${fixtures.metadata.n_landmarks}`,
);

// 2. buildFrameFeatures byte-identical packing.
const jsPacked = buildFrameFeatures(fixtures.raw_frame);
let packedMatches = jsPacked.features.length === fixtures.packed_features.length;
if (packedMatches) {
  for (let i = 0; i < jsPacked.features.length; i++) {
    if (Math.abs(jsPacked.features[i] - fixtures.packed_features[i]) > 1e-6) {
      packedMatches = false;
      console.error(
        `    first packed mismatch at i=${i}: js=${jsPacked.features[i]} py=${fixtures.packed_features[i]}`,
      );
      break;
    }
  }
}
check("buildFrameFeatures features byte-identical", packedMatches);

let missingMatches = jsPacked.missing.length === fixtures.packed_missing.length;
if (missingMatches) {
  for (let i = 0; i < jsPacked.missing.length; i++) {
    const jsBool = jsPacked.missing[i] !== 0;
    const pyBool = !!fixtures.packed_missing[i];
    if (jsBool !== pyBool) {
      missingMatches = false;
      console.error(`    first missing mismatch at lm=${i}: js=${jsBool} py=${pyBool}`);
      break;
    }
  }
}
check("buildFrameFeatures missing byte-identical", missingMatches);

// 3. normalizeSequence near-identical (1e-4 tolerance for f32 round-trip).
const T = fixtures.metadata.n_frames_for_normalize;
const inFeatures = new Float32Array(fixtures.normalized_input_features);
const inMissing = new Uint8Array(fixtures.normalized_input_missing.length);
for (let i = 0; i < fixtures.normalized_input_missing.length; i++) {
  inMissing[i] = fixtures.normalized_input_missing[i] ? 1 : 0;
}
const jsNorm = normalizeSequence(inFeatures, inMissing, T);

let normMatches = jsNorm.length === fixtures.normalized_features.length;
let maxDiff = 0;
let maxDiffI = -1;
if (normMatches) {
  for (let i = 0; i < jsNorm.length; i++) {
    const d = Math.abs(jsNorm[i] - fixtures.normalized_features[i]);
    if (d > maxDiff) {
      maxDiff = d;
      maxDiffI = i;
    }
  }
  if (maxDiff > 1e-4) {
    normMatches = false;
    console.error(
      `    normalize diff at i=${maxDiffI}: js=${jsNorm[maxDiffI]} py=${fixtures.normalized_features[maxDiffI]} diff=${maxDiff}`,
    );
  }
}
check(`normalizeSequence within 1e-4 (max diff ${maxDiff.toExponential(2)})`, normMatches);

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
