/**
 * Numerical-parity tests for the TypeScript landmark packer against the
 * canonical Python implementation.
 *
 * The fixture landmark_fixtures.json is regenerated by
 * openhand-model/scripts/dump_landmark_vectors.py whenever the canonical
 * Python pipeline changes. We assert that buildFrameFeatures packs
 * features byte-identically with the Python build_frame_features output.
 *
 * If this test fails, the TS port has drifted from training-time Python
 * code and the deployed CTC model will silently produce nonsense.
 */

import { describe, expect, it } from "vitest";

import {
  FRAME_FEATURES,
  FRAME_LANDMARKS,
  buildFrameFeatures,
} from "../landmarks";
import fixtures from "./landmark_fixtures.json";

describe("landmarks parity (Python vs TypeScript)", () => {
  it("derived constants match the fixture", () => {
    expect(FRAME_FEATURES).toBe(fixtures.metadata.n_features);
    expect(FRAME_LANDMARKS).toBe(fixtures.metadata.n_landmarks);
  });

  it("buildFrameFeatures packs features byte-identically", () => {
    const out = buildFrameFeatures(fixtures.raw_frame);
    expect(out.features.length).toBe(fixtures.packed_features.length);

    for (let i = 0; i < out.features.length; i++) {
      expect(out.features[i]).toBeCloseTo(fixtures.packed_features[i], 6);
    }
  });

  it("buildFrameFeatures produces the expected missing mask", () => {
    const out = buildFrameFeatures(fixtures.raw_frame);
    expect(out.missing.length).toBe(fixtures.packed_missing.length);
    for (let i = 0; i < out.missing.length; i++) {
      const jsBool = out.missing[i] !== 0;
      const pyBool = !!fixtures.packed_missing[i];
      expect(jsBool).toBe(pyBool);
    }
  });
});
